### ISSUE TITLE
umbrella: fix current node-editing system

### ISSUE THREAD

**Issue by rchanou** [rchanou/liana#16]
- [x] don't auto-move after edit anymore?
- [x] a few cases broken from latest refactor (e.g. error when trying to change op)
- [x] auto-scroll to keep cursor in view
- [ ] allow customization of input mode display
